name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - uses: peaceiris/actions-gh-pages@v3
        permissions:
          contents: write
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
